version: 2.1

workflows:
  build_test:
    jobs:
      - build
      - test:
          requires:
            - build

# This defines a reusable executor.
executors:
  php-only:
    docker:
      - image: circleci/php:7.3.19-node

  cypress-and-wordpress:
    docker:
      - image: circleci/php:7.3.19-node
      - image: circleci/mysql:8.0.16
        environment:
          MYSQL_DATABASE: wordpress
          MYSQL_ROOT_PASSWORD: password
      - image: wordpress:5.4.2-php7.3-apache
        environment:
          WORDPRESS_DB_PASSWORD: password
          WORDPRESS_DB_HOST: db
#      - image: cypress/browsers:node12.13.0-chrome78-ff70
#        environment:
#          TERM: xterm

references:
  workspace_root: &workspace_root
    /home/circleci/project
  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

  # Default container configuration.
  default_config: &default_config
    environment:
      - DEFAULT_COMPOSER_FLAGS: "--no-interaction --no-progress --no-suggest --prefer-dist"
    working_directory: *workspace_root

  # Environment set-up.
  configure_environment: &configure_environment
    run:
      # xdebug is slow; hirak/prestissimo enables parallel Composer downloads.
      name: "Configure System"
      command: |
        sudo rm /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
        echo 'memory_limit=4096M' | sudo tee -a /usr/local/etc/php/conf.d/circleci.ini
        echo 'error_log=/home/circleci/php.log' | sudo tee -a /usr/local/etc/php/conf.d/circleci.ini
        composer global require $DEFAULT_COMPOSER_FLAGS hirak/prestissimo

jobs:
  build:
    <<: *default_config
    executor: php-only
    steps:
      - checkout:
          path: project
      - *configure_environment
      - setup_remote_docker
      - run:
          name: "Install Project Dependencies"
          command: cd project && composer install $DEFAULT_COMPOSER_FLAGS && npm install
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - project

  test:
    <<: *default_config
    executor: cypress-and-wordpress
    steps:
      - *configure_environment
      - setup_remote_docker
      - *attach_workspace
      - run:
          name: "Set up network"
          command: |
            set -x
            docker network create wp-network
